// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WardrobeApi.Data;

#nullable disable

namespace WardrobeApi.Data.Migrations
{
    [DbContext(typeof(WardrobeContext))]
    partial class WardrobeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("WardrobeApi.Data.Models.ClothingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClothingItems");
                });

            modelBuilder.Entity("WardrobeApi.Data.Models.Outfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("WardrobeApi.Data.Models.OutfitItem", b =>
                {
                    b.Property<int>("OutfitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClothingItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OutfitId", "ClothingItemId");

                    b.HasIndex("ClothingItemId");

                    b.ToTable("OutfitItem");
                });

            modelBuilder.Entity("WardrobeApi.Data.Models.OutfitItem", b =>
                {
                    b.HasOne("WardrobeApi.Data.Models.ClothingItem", "ClothingItem")
                        .WithMany("OutfitItems")
                        .HasForeignKey("ClothingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WardrobeApi.Data.Models.Outfit", "Outfit")
                        .WithMany("OutfitItems")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClothingItem");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("WardrobeApi.Data.Models.ClothingItem", b =>
                {
                    b.Navigation("OutfitItems");
                });

            modelBuilder.Entity("WardrobeApi.Data.Models.Outfit", b =>
                {
                    b.Navigation("OutfitItems");
                });
#pragma warning restore 612, 618
        }
    }
}
